version: "3.9"
services:
  mariadb:
    image: mariadb:11.4
    container_name: camp_toolkit
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
